# Generated by Django 5.0.7 on 2024-08-08 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_remove_option_is_correct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='course_title',
            new_name='course',
        ),
    ]
