# Generated by Django 5.0.7 on 2024-08-09 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_remove_student_progress_score_student_progress_quiz_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='student_progress',
        ),
    ]
