# Generated by Django 5.0.7 on 2024-08-09 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_studentprogress'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OverallProgress',
        ),
    ]
