# Generated by Django 5.0.7 on 2024-08-09 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_overallprogress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='overallprogress',
            name='question',
        ),
    ]
