# Generated by Django 5.0.6 on 2024-07-22 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_learning_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdf',
            name='pdf_des',
            field=models.CharField(default='', max_length=200),
        ),
    ]
