# Generated by Django 5.0.7 on 2024-07-28 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_learning_app', '0006_alter_studentprogress_student_delete_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='is_correct',
        ),
    ]
