# Generated by Django 5.0.7 on 2024-07-28 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_learning_app', '0007_remove_answer_is_correct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='options',
            name='question',
        ),
        migrations.RemoveField(
            model_name='studentprogress',
            name='selected_option',
        ),
        migrations.RemoveField(
            model_name='question',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='studentprogress',
            name='question',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='course',
        ),
        migrations.RemoveField(
            model_name='studentprogress',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='studentprogress',
            name='student',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Options',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
        migrations.DeleteModel(
            name='StudentProgress',
        ),
    ]
