# Generated by Django 5.0.6 on 2024-07-22 15:27

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_img', models.ImageField(upload_to='profile_img')),
                ('bio', models.TextField()),
                ('age', models.PositiveIntegerField()),
                ('address', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=12, validators=[django.core.validators.MinLengthValidator(10, message='Phone Number should be 10 charcter long')])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
