# Generated by Django 5.0.6 on 2024-07-23 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_studentprofile_goals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='age',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='age',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
