# Generated by Django 5.0.7 on 2024-07-26 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_studentmodel_teachermodel_aboutteacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutteacher',
            name='teacher',
        ),
        migrations.DeleteModel(
            name='StudentModel',
        ),
        migrations.DeleteModel(
            name='AboutTeacher',
        ),
        migrations.DeleteModel(
            name='TeacherModel',
        ),
    ]
