# Generated by Django 5.0.6 on 2024-07-26 15:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cartitem_is_paid'),
        ('online_learning_app', '0002_pdf_pdf_des'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('payment_id', models.CharField(max_length=200)),
                ('paid_at', models.DateTimeField()),
                ('cart_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='cart.cartitem')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_learning_app.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enroll_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_learning_app.course')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='cart.payment')),
            ],
        ),
    ]
