# Generated by Django 5.0.7 on 2024-07-26 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_payment_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='is_enroll',
            field=models.BooleanField(default=False),
        ),
    ]
