# Generated by Django 5.0.7 on 2024-07-30 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_enrollment_is_enroll'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='cart_item',
        ),
    ]
